### ISSUE TITLE
KeyError: 'serialization'

### ISSUE THREAD

**Issue by tgoelles** [codemation/easycharts#2]
I get an error when trying to run the example:

```
10-06 12:54:36 uvicorn.error INFO     connection open
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/miniconda/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 203, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/miniconda/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/miniconda/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/miniconda/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/miniconda/lib/python3.8/site-packages/starlette/middleware/errors.py", line 146, in __call__
    await self.app(scope, receive, send)
  File "/miniconda/lib/python3.8/site-packages/starlette/exceptions.py", line 58, in __call__
    await self.app(scope, receive, send)
  File "/miniconda/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/miniconda/lib/python3.8/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/miniconda/lib/python3.8/site-packages/starlette/routing.py", line 68, in app
    await func(session)
  File "/miniconda/lib/python3.8/site-packages/easyrpc/server.py", line 250, in origin
    serialization = setup['serialization']
KeyError: 'serialization'
10-06 12:54:36 uvicorn.error ERROR    Exception in ASGI application
Traceback (most recent call last):
  File "/miniconda/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 203, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/miniconda/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/miniconda/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/miniconda/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/miniconda/lib/python3.8/site-packages/starlette/middleware/errors.py", line 146, in __call__
    await self.app(scope, receive, send)
  File "/miniconda/lib/python3.8/site-packages/starlette/exceptions.py", line 58, in __call__
    await self.app(scope, receive, send)
  File "/miniconda/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/miniconda/lib/python3.8/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/miniconda/lib/python3.8/site-packages/starlette/routing.py", line 68, in app
    await func(session)
  File "/miniconda/lib/python3.8/site-packages/easyrpc/server.py", line 250, in origin
    serialization = setup['serialization']
KeyError: 'serialization'
INFO:     connection closed
```

I created a new conda env and just installed the depenencies

**Comment by codemation** [comment]
Hi @tgoelles, thanks for opening this issue. 

This is a BUG introduced with newer versions of [easyrpc](https://github.com/codemation/easyrpc), which requires 'serialization' to be passed along with the setup of the easyrpc communication flow.  

This is now fixed in version 0.106 of [easycharts](https://pypi.org/project/easycharts/) 

Let me know if this solves your issue and please update / close issue when you can.

**Comment by tgoelles** [comment]
Hi. Thanks for the quick response.

I should have time to test this again next week.
